#!/usr/bin/env node

const { Client } = require('pg');
const { argv } = require('node:process');

function logAndExit(err) {
  console.log(err);
  process.exit(1);
};

class ExpenseData {
  constructor() {
    this.client = new Client({ database: 'expenses' });
  }

  async addExpense(amount, memo) {
    await this.client.connect().catch(error => logAndExit(error));
    let date = (new Date()).toLocaleDateString();
    let query = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3) RETURNING *';
    let values = [amount, memo, date];

    await this.client.query(query, values)
      .catch(error => logAndExit(error));
    this.client.end().catch(error => logAndExit(error));
  }

  async listExpenses() {
    await this.client.connect().catch(error => logAndExit(error));

    let data = await this.client.query('SELECT * FROM expenses ORDER BY created_on ASC')
      .catch(error => logAndExit(error));
    this.displayExpenses(data);

    this.client.end().catch(error => logAndExit(error));
  }

  async searchExpenses(searchTerm) {
    await this.client.connect().catch(error => logAndExit(error));
    let query = 'SELECT * FROM expenses WHERE memo ILIKE $1';
    let data = await this.client.query(query, [`%${searchTerm}%`])
      .catch(error => logAndExit(error));
    this.displayExpenses(data);
    this.client.end().catch(error => logAndExit(error));
  }

  displayExpenses(data) {
    data.rows.forEach(row => {
    let { id, amount, memo, created_on } = row;
      console.log(`${String(id).padStart(3)} | ${created_on.toDateString().padStart(10)} | ${amount.padStart(12)} | ${memo}`);
    });
  }
}

class CLI {
  static HELP() {
    return `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field
`;
  }
  constructor() {
    this.expenses = new ExpenseData();
  }

  displayHelp() {
    console.log(CLI.HELP());
  }

  run(parameters) {
    let command = parameters[2];
    if (command === 'list') {
      this.expenses.listExpenses();
    } else if (command === 'add') {
      let [ amount, memo ] = argv.slice(3);
      if (amount && memo) {
        this.expenses.addExpense(amount, memo);
      } else {
        console.log('You must provide an amount and memo.');
      }
    } else if (command === 'search') {
      this.expenses.searchExpenses(argv[3]);
    } else {
      this.displayHelp();
    }
  }
}


let cli = new CLI();
cli.run(argv);